"use strict";
exports.__esModule = true;
var message = 'Hello World';
console.log(message);
var x = 20;
var y = 20;
var sum;
var title = "Typescript";
var isBeginner = true;
var total = 0;
var name = "Seil";
var sentence = "My name is " + name + "\nI am a beginner in Typescript";
console.log(sentence);
var n = null;
var u = undefined;
var isNew = null;
var myName = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
